export const confirmModalConst = {
  label: {
    confirm: "確認",
    update: "更新",
    save: "保存",
    delete: "削除",
    applicationCancel: "取消",
  },
  button: {
    ok: "OK",
    cancel: "キャンセル",
    close: "閉じる",
    save: "保存",
    update: "更新",
    delete: "削除",
    applicationCancel: "取消",
    regulate: "調整",
  },
  message: {
    logout: "ログアウトします。よろしいですか?",
    saveApprovalGroup:"承認グループを保存します。よろしいですか?",
    deleteApprovalGroup:"承認グループを削除します。よろしいですか?",
    changePassword: "変更します。よろしいですか?",
    saveUser: "保存します。よろしいですか?",
    saveApplication: "保存します。よろしいですか?",
    submitApplication: "申請します。よろしいですか?",
    deleteApplication: "削除します。よろしいですか?",
    cancelApplication: "取消します。よろしいですか?",
    approvalApplication: "承認します。よろしいですか?",
    rejectApplication: "差戻します。よろしいですか?",
    settingGrantDays: "付与情報が未設定の期間を対象に付与日数を設定します。よろしいですか?",
    saveCareer: "保存します。よろしいですか?",
    deleteCareer: "削除します。よろしいですか?",
    deleteCareerItem: "項目を削除します。よろしいですか?",
  }
} as const