export const pageCommonConst = {
  path : {
    login: "/",
    dashboard: "/dashboard",
    application: "/application",
    adminApplication: "/admin/application",
    applicationNew: "/application/new",
    approval: "/approval",
    user: "/user",
    settingSystem: "/setting/system",
    settingSystemGrantRule: "/setting/system?tab=grantRule",
    settingSystemApprovalGroup: "/setting/system?tab=approvalGroup",
    settingUser: "/setting/user",
    settingUserEditPersonal: "/setting/user?tab=editPersonal",
    settingUserEditPassword: "/setting/user?tab=editPassword",
    career: "/career",
    careerList: "/career/list",
    careerSetting: "/career/setting",
  },
  pageName: {
    login: "ログイン",
    dashboard: "ダッシュボード",
    application: "申請一覧",
    applicationConfirm: "申請確認",
    applicationEdit: "申請",
    adminApplication: "申請管理",
    applicationNew: "新規申請",
    approval: "承認一覧",
    approvalEdit: "承認",
    user: "ユーザ管理",
    userEdit: "ユーザ編集",
    settingSystem: "システム管理",
    settingSystemGrantRule: "付与日数",
    settingSystemApprovalGroup: "承認グループ",
    settingUser: "個人設定",
    settingUserEditPersonal: "個人情報編集",
    settingUserEditPassword: "パスワード変更",
    career: "スキル管理",
    careerList: "経歴情報一覧",
    careerEdit: "経歴情報編集",
    careerNew: "新規登録",
    careerSetting: "経歴情報項目マスタ",
    logout: "ログアウト",
  },
  tabName: {
    editPersonal: "editPersonal",
    editPassword: 'editPassword',
    grantRule: "grantRule",
    approvalGroup: 'approvalGroup',
  },
  param: {
    id: "id",
    tab: "tab",
    applicationId: "applicationId",
    selectDate: "selectDate",
    isNew: "isNew",
    userId: "userId",
    taskId: "taskId",
    ref: "ref",
    careerId: "careerId",
  },
  notSupportMessage: "Not supported device",
} as const