export const pageCommonConst = {
  path : {
    // 共通
    login: "/",
    dashboard: "/dashboard",
    application: "/application",
    applicationNew: "/application/new",
    approval: "/approval",
    settingUser: "/setting/user",
    settingUserEditPersonal: "/setting/user?tab=editPersonal",
    settingUserEditPassword: "/setting/user?tab=editPassword",
    career: "/career",
    careerList: "/career/list",
    careerDownload: "/career/download",
    careerMemberList: "/career/memberList",
    // 管理者メニュー
    adminApplication: "/admin/application",
    adminBook: "/admin/book",
    adminBookDownload: "/admin/book/download",
    adminSetting: "/admin/setting",
    adminSettingGrantRule: "/admin/setting?tab=grantRule",
    adminSettingApprovalGroup: "/admin/setting?tab=approvalGroup",
    adminSettingCareerItem: "/admin/setting?tab=career",
    adminUser: "/admin/user",
  },
  pageName: {
    // 共通
    login: "ログイン",
    logout: "ログアウト",
    dashboard: "ダッシュボード",
    application: "申請一覧",
    applicationConfirm: "申請確認",
    applicationEdit: "申請",
    applicationNew: "新規申請",
    aggregateApplication: "有給休暇集計",
    approval: "承認一覧",
    approvalEdit: "承認",
    settingUser: "個人設定",
    settingUserEditPersonal: "個人詳細情報",
    settingUserEditPassword: "パスワード変更",
    career: "スキル管理",
    careerDashboard: "ダッシュボード",
    careerList: "経歴情報一覧",
    careerDownload: "",
    careerEdit: "経歴情報編集",
    careerNew: "新規登録",
    careerMemberList: "保有スキル一覧",
    // 管理者メニュー
    adminApplication: "申請管理",
    adminBook: "有給休暇集計",
    adminBookDownload: "",
    adminSetting: "システム管理",
    adminSettingGrantRule: "付与日数設定",
    adminSettingApprovalGroup: "承認グループ設定",
    adminSettingCareerItem: "経歴情報項目設定",
    adminUser: "ユーザ管理",
    adminUserEdit: "ユーザ編集",
    adminUserNew: "新規登録",
  },
  tabName: {
    editPersonal: "editPersonal",
    editPassword: 'editPassword',
    grantRule: "grantRule",
    approvalGroup: 'approvalGroup',
    career: 'career',
  },
  param: {
    id: "id",
    tab: "tab",
    applicationId: "applicationId",
    selectDate: "selectDate",
    isNew: "isNew",
    userId: "userId",
    taskId: "taskId",
    ref: "ref",
    careerId: "careerId",
    months: "months",
  },
  notSupportMessage: "Not supported device",
} as const