"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';

import '@/assets/styles/index.css';
import Header from '@/components/header';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head />
      <body>
        <Header />
        <div className='content-body'>
          {children}
        </div>
      </body>
    </html>
  )
}
