"use client"

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import "bootstrap-icons/font/bootstrap-icons.css"

import '@/assets/styles/index.css';
import { ConfirmProvider } from '@/contexts/confirmProvider';
import Header from '@/components/header';
import { useUserInfoStore } from '@/store/userInfoStore';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // 共通Store
  const { getUserInfo, isAdmin } = useUserInfoStore();

  return (
    <html>
      <head />
      {/* <body className={inter.className}> */}
      <body>
        <div hidden={!getUserInfo()?.id}>
          <Header />
        </div>
        <ConfirmProvider>
          <div className="content-body">
            {children}
          </div>
        </ConfirmProvider>
      </body>
    </html>
  )
}
